import {
	  PUBLIC_AFFILIATE_REPORT_URL = '',
	  PUBLIC_AFFILIATE_DISPUTE_URL = '',
	  PUBLIC_AFFILIATE_CREDIT_CHECK_URL = ''
} from '$env/static/public';

export const AFFILIATE_LINKS = {
	  report: PUBLIC_AFFILIATE_REPORT_URL,
	  dispute: PUBLIC_AFFILIATE_DISPUTE_URL,
	  creditCheck: PUBLIC_AFFILIATE_CREDIT_CHECK_URL
};